main: uk.co.catlord.spigot.MCTreasureHuntPlugin.App
name: MCTreasureHuntPlugin
version: dev
api-version: 1.19
commands:
  give-treasure-token:
    description: Gives a player some number of Time Shards
    usage: "Usage: /give-treasure-token <count>"
  set-treasure-chest:
    description: Sets a chest as a treasure chest
    usage: "Usage: /set-treasure-chest <x> <y> <z> <checkpoint>"
  delete-treasure-chest:
    description: Deletes a treasure chest
    usage: "Usage: /delete-treasure-chest <x> <y> <z>"
  reset-treasure-hunt:
    description: Resets the treasure hunt
    usage: "Usage: /reset-treasure-hunt <password>"
  set-checkpoint:
    description: Set a checkpoint
    usage: "Usage: /set-checkpoint <x> <y> <z> <name> <previous-checkpoint> <radius>"
  set-start:
    description: Set the start
    usage: "Usage: /set-start <x> <y> <z>"
  set-finish:
    description: Set the finish
    usage: "Usage: /set-finish <x> <y> <z> <previous-checkpoint>"
  set-player-time:
    description: Set the time for a player
    usage: "Usage: /set-player-time <player> <hours> <minutes> <seconds>"
  my:
    description: Get your stats
    usage: "Usage: /my <stat>"
  compass:
    description: Get a treasure compass
    usage: "Usage: /compass"
  set-treasure-beacon:
    description: Set a treasure beacon
    usage: "Usage: /set-treasure-beacon <x> <y> <z> <name> <trail-from> <radius> <difficulty>"
