name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      commit:
        description: 'Full commit hash'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        make build

    - name: Prepare Build Artifacts
      id: prepare-build-artifacts
      env:
        VERSION: ${{ inputs.version }}
      run: |
        PLUGIN_ARTIFACT_PATH="target/MCTreasureHuntPlugin-$VERSION.jar"
        mv "target/MCTreasureHuntPlugin-latest.jar" "$PLUGIN_ARTIFACT_PATH"
        echo "plugin-artifact-path=$PLUGIN_ARTIFACT_PATH" >> $GITHUB_OUTPUT

    - uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.prepare-build-artifacts.outputs.plugin-artifact-path }}
        commit: ${{ inputs.commit }}
        generateReleaseNotes: true
        tag: ${{ inputs.version }}
